name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies and package Lambda
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary -t lambda_pkg
          cp lambda_function.py lambda_pkg/
          cd lambda_pkg
          zip -r ../lambda_deploy.zip .

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: logStatsFunction
          zip_file: lambda_deploy.zip
